update health check
LT-Students/DigitalOffice-CompanyService pull request #15
Opened 2021-04-05 17:14 UTC by borovHokage

http://outsourcing.nat.tepkom.ru:20080/redmine/issues/246

Task #309: Remove UseHealthChecks
Task #310: Map healthcheck endpoint to '/{serviceID}/hc' | 
Task #311: Add RabbitMQ healthcheck
Task #312: Add SQL Server healthcheck 
Feature #313: Rework healthcheck endpoint response

2021-04-05 17:47 UTC, BelehovEgor requested changes

2021-04-05 17:47 UTC, BelehovEgor commented on src/CompanyService/Startup.cs
>              services.AddHealthChecks();
remove this line. You have it below

2021-04-05 20:23 UTC, borovHokage commented on src/CompanyService/Startup.cs
>              services.AddHealthChecks();
done

2021-04-05 20:38 UTC, BelehovEgor approved these changes

2021-04-06 14:30 UTC, KostinP approved these changes

2021-04-06 21:18 UTC, merged